version: '3.8'
services:
  web:
    image: python:latest
    ports:
      - 3001:3001
    volumes:
      - .:/app
    working_dir: /app
    command:  sh -c "pip install --no-cache-dir -r requirements.txt && python server.py"